#!/bin/bash

docker stop lukasjoc_devel || true && \
docker rm lukasjoc_devel || true && \
docker build -t lukasjoc:devel -f docker/Dockerfile . && \
# docker run --name lukasjoc_devel -v $PWD/docker/default:/etc/nginx/sites-enabled/default -d -p 80:80 lukasjoc:devel
docker run --name lukasjoc_devel -v $PWD/docker/nginx.conf:/etc/nginx.conf:ro -d -p 80:80 lukasjoc:devel

# if ! [ -d node_modules ]; then
# 	npm install
# fi
# 
# npm run serve
