#!/bin/bash

docker stop lukasjoc_devel || true
docker rm lukasjoc_devel || true
docker build -t lukasjoc:devel -f docker/Dockerfile .

docker run --name lukasjoc_devel -p "80:80" -d lukasjoc:devel

# if ! [ -d node_modules ]; then
# 	npm install
# fi
# 
# npm run serve
