---
version: "3.7"

networks:
  PROXY_NETWORK:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: lukasjoc:latest
    container_name: lukasjoc
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.httpsredirect.redirectscheme.scheme=https"
      - "traefik.http.routers.lukasjoc.middlewares=httpsredirect"
      - "traefik.http.routers.lukasjoc.entrypoints=http"
      - "traefik.http.routers.lukasjocsecure.tls=true"
      - "traefik.http.routers.lukasjocsecure.entrypoints=https"
      - "traefik.http.routers.lukasjocsecure.tls.certresolver=http01challenge"
      - "traefik.http.routers.lukasjoc.rule=Host(`lukasjoc.com`, `www.lukasjoc.com`)"
      - "traefik.http.routers.lukasjocsecure.rule=Host(`lukasjoc.com`, `www.lukasjoc.com`)"
    restart: always
    networks:
      - PROXY_NETWORK

