---
version: "3.7"
networks:
  PROXY_NETWORK:
    external: true
services:
  website:
      build:
        context: .
        dockerfile: docker/Dockerfile
      image: lukasjoc:latest
      container_name: lukasjoc
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.lukasjoc.middlewares=https-redirect"
        - "traefik.http.routers.lukasjoc.entrypoints=http"
        - "traefik.http.routers.lukasjoc-secure.tls=true"
        - "traefik.http.routers.lukasjoc-secure.entrypoints=https"
        - "traefik.http.routers.lukasjoc-secure.tls.certresolver=http-01-challenge"
        - "traefik.http.routers.lukasjoc.rule=Host(`lukasjoc.com`, `www.lukasjoc.com`)"
        - "traefik.http.routers.lukasjoc-secure.rule=Host(`lukasjoc.com`, `www.lukasjoc.com`)"
      restart: always
      networks:
        - PROXY_NETWORK
