#!/bin/bash
# Rendering/Build script. Markdown content to html with template
# 
# Usage:
#  ./render [single flag]
#  
# Flags:
#  -s         build the bundle and expose as docker container
#  -b         build the bundle to build/ dir
#  --version  print current version of this script
#  --help     this message
# 
# Use "./render --help" for more information about this script.

set -u

declare _RENDER_VERSION="v0.3"

# print current version of this srcipt
__version() { echo "render version v0.3"; }

# print usage information
__usage() {
  cat <<EOF
Rendering/Build script. Markdown content to html with template

Usage:
 ./render [a single flag]
 
Flags:
 -s         build the bundle and expose as docker container
 -b         build the bundle to build/ dir
 -v         print current version of this script ($_RENDER_VERSION)

 Use "./render --help" for more information about this script.
 --help     this message
EOF
}

build() {
  # check if pandoc is installed
  if ! command -v "pandoc" >/dev/null 2>&1; then echo "Pandoc is a requirement!!"; exit 1; fi

  local build_dir="$PWD/build"
  local assets_dir="$PWD/assets/"
  local etc_dir="$PWD/etc/"

  # Create build dir if needed
  [ ! -d "$build_dir" ]; mkdir -p "$build_dir"
  [ -d "$build_dir" ]; rm -rf "$build_dir"; mkdir -p "$build_dir"

  # Prepare assets and 
  cp -a "$assets_dir" "$build_dir"
  cp -a "$etc_dir" "$build_dir"

  # build markdown files and add to build_dir
  local pages="$PWD/pages"
  for candidate in "$pages"/*.md; do
    pandoc \
      --from markdown \
      --to html "$candidate" \
      --template="$PWD"/default.html \
      -o "$build_dir/$(basename "${candidate%.*}").html"
    done
    tree "$build_dir"
    return 0
  }

serve() {
  docker stop lukasjoc_latest || true
  docker rm lukasjoc_latest || true

  # build the image
  docker build \
    -t lukasjoc:latest \
    -f docker/Dockerfile "$PWD"

  # use image to create the container on port 80
  docker run \
    --name lukasjoc_latest \
    -p "80:80" \
    -d lukasjoc:latest

  return 0
}

# print help if zero args are given
if [[ "$#" == "0" ]]; then __usage; fi

while [[ "$#" -ne 0 ]]; do
  case "$1" in
    -s) serve;;
    -b) build;;
    -v) echo "render version $_RENDER_VERSION"; exit 0;;
    --help) __usage; exit 0;;
    *) __usage; exit 0;;
  esac
  shift
done
