#!/bin/bash

podman stop lukasjoc_latest || true
podman rm lukasjoc_latest || true

# build the image
podman build \
  -t lukasjoc:latest \
  -f docker/Dockerfile "$PWD"

# use image to create the container on port 80
podman run \
  --name lukasjoc_latest \
  -p "80:80" \
  -d lukasjoc:latest

return 0
