# this shuld work broo
# wwopork
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /usr/share/nginx/html;
	location / {
		try_files \index.html $uri $uri/ =404;
 		index  index.html index.htm;
	}
	
	location ~ /\.ht {
  	deny all;
	}

	error_page 404 /40x.html;
	location  /40x.html {
		root /usr/share/nginx/html;
		internal;
	}

}
