server {

	listen 80;
	server_name localhost;

 	normal pages 		
 		location / {
 		root   /usr/share/nginx/html;
 		try_files $uri $uri/ /index.html;
 		index  index.html index.htm;
 	}
	

	# error pages
	error_page 400 404 405 408 410 429 /40x.html;
	location  /40x.html {
		root /usr/share/nginx/html;
	  internal;
	}
	
	error_page   500 502 503 504  /50x.html;
	location = /50x.html {
		root   /usr/share/nginx/html;
		internal;
	}
	
}
