name: Try to build markdown files using pandoc

x-branches: &branches
  branches: [ main ]

on:
  push:
    <<: *branches
  pull_request:
    <<: *branches

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Check if container build works
      run: ./render serve

