name: Try to build markdown files using pandoc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: docker://pandoc/core:2.9
      - run: ./render -s
